Fixes #18237: cli rework: doc
Normation/rudder pull request #3224
Opened 2020-09-21 14:13 UTC by gpoblon

https://issues.rudder.io/issues/18237

2020-09-29 21:16 UTC, peckpeck commented
This pr needs a rebase

2020-09-30 07:02 UTC, gpoblon commented
PR rebased

2020-09-30 07:06 UTC, gpoblon commented
Commit modified

2020-09-30 08:59 UTC, peckpeck requested changes

2020-09-30 08:59 UTC, peckpeck commented on rudder-lang/docs/usage.adoc
> +* technique read: generates a JSON technique from a RudderLang technique
add that this is a json in the technique editor format

2020-09-30 08:59 UTC, peckpeck commented on rudder-lang/docs/usage.adoc
> +* technique generate: generates a JSON object that comes with RudderLang + DSC + CFEngine technique from a JSON technique. Please note that by exception, `--stdin` and `--stdout` options are default
i think technique read should also use stdin by default

2020-09-30 08:59 UTC, peckpeck commented on rudder-lang/docs/usage.adoc
> +Any information log is displayed to `SDTOUT`, errors should be printed to `STDERR`. JSON log format handled. JSON output (including logs) is optional for compile and migrate but is default behavior f
This is not easy to understand, could you rephrase this ?

2020-09-30 08:59 UTC, peckpeck commented on rudder-lang/docs/usage.adoc
> +Rudderc abilities are callable through subcommands, namely <technique read>, <technique generate>, <migrate>, <compile>,
abilities ?

2020-09-30 08:59 UTC, peckpeck commented on rudder-lang/docs/usage.adoc
> +        --stdout       Takes stdout as an output rather than using a file. Overwrites output file option. Dismiss logs, including errors
errors are on stderr why are they dismissed ?

2020-09-30 13:16 UTC, gpoblon commented
PR updated with a new commit

2020-09-30 14:15 UTC, peckpeck approved these changes

2020-09-30 14:40 UTC, gpoblon commented
OK, squash merging this PR

2020-09-30 14:41 UTC, merged