Fixes #18317: Support source package in Rudder inventory
Normation/rudder pull request #3251
Opened 2020-10-09 22:01 UTC by VinceMacBuche

https://issues.rudder.io/issues/18317

2020-10-11 17:14 UTC, VinceMacBuche commented
PR updated with a new commit

2020-10-12 16:41 UTC, fanf commented on webapp/sources/ldap-inventory/inventory-provisioning-core/src/main/scala/com/normation/inventory/ldap/provisioning/SoftwareIdFinder.scala
> +        merged.find { x => x == s } match {
I don't think we want to compare ALL fields ? Only name, version, source name, source version ?

2020-10-12 21:02 UTC, VinceMacBuche commented
PR updated with a new commit

2020-10-21 12:13 UTC, fanf requested changes

2020-10-21 12:13 UTC, fanf commented on webapp/sources/ldap-inventory/inventory-repository/src/main/resources/ldap/inventory.schema
> +        licenseExpirationDate $ licenseName $ licenseProductId $ licenseProductKey $ sourceName $ sourceVersion ) )
`sourceName` and `sourceVersion` attributeType must be defined before use

2020-10-22 08:52 UTC, VinceMacBuche commented
PR updated with a new commit

2020-10-22 08:53 UTC, VinceMacBuche commented
PR updated with a new commit

2020-10-22 08:55 UTC, fanf approved these changes

2020-10-22 08:56 UTC, Normation-Quality-Assistant commented
This PR is not mergeable to upper versions.
Since it is "Ready for merge" you must merge it by yourself using the following command:
`rudder-dev merge https://github.com/Normation/rudder/pull/3251`
-- Your faithful QA
Kant merge: "Science is organized knowledge. Wisdom is organized life."
 (https://ci.normation.com/jenkins/job/merge-accepted-pr/31387/console)

2020-10-22 08:59 UTC, VinceMacBuche commented
OK, squash merging this PR

2020-10-22 09:00 UTC, merged