Fixes #18375: Directly generate policies with correct rights
Normation/rudder pull request #3280
Opened 2020-10-20 22:28 UTC by fanf

https://issues.rudder.io/issues/18375

2020-10-21 05:01 UTC, ncharles requested changes
This is really great !
Just a typo, and  question on changing permissions applied for root

2020-10-21 05:01 UTC, ncharles commented on webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/policies/write/PolicyWriterService.scala
> +  val filePerms      = Set[PosixFilePermission](OWNER_READ, OWNER_WRITE, GROUP_READ)
i know it's nt introduced by this PR, but permissions for root ought to be 600 (we have policies that change it when agent is ran)
Do you think you can make a specific case for that ?

2020-10-21 16:49 UTC, ncharles approved these changes

2020-10-21 16:50 UTC, Normation-Quality-Assistant commented
This PR is not mergeable to upper versions.
Since it is "Ready for merge" you must merge it by yourself using the following command:
`rudder-dev merge https://github.com/Normation/rudder/pull/3280`
-- Your faithful QA
Kant merge: "Live your life as though your every act were to become a universal law."
 (https://ci.normation.com/jenkins/job/merge-accepted-pr/31351/console)

2020-10-22 07:49 UTC, fanf commented
OK, squash merging this PR

2020-10-22 07:50 UTC, fanf commented
OK, squash merging this PR

2020-10-22 09:52 UTC, fanf commented
OK, merging this PR

2020-10-22 10:25 UTC, fanf commented
OK, merging this PR

2020-10-22 16:39 UTC, fanf commented
OK, squash merging this PR

2020-10-22 16:40 UTC, merged