Fixes #18931: No skipped directives on Rule screen after parent ticket
Normation/rudder pull request #3514
Opened 2021-02-19 18:00 UTC by fanf

https://issues.rudder.io/issues/18931

2021-02-19 18:03 UTC, fanf commented
PR updated with a new commit

2021-02-19 18:05 UTC, fanf commented
PR updated with a new commit

2021-02-19 21:23 UTC, ncharles requested changes
i am very surprised the change is so small, i ould have thought the impact of this would have been greater
can you correct the comment and self merge?

2021-02-19 21:23 UTC, ncharles commented on webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/reports/ReportingService.scala
> +  def findDirectiveRuleStatusReportsByRule(ruleId: RuleId): Box[Map[NodeId, NodeStatusReport]]
i would love if you could change the comment

2021-02-20 09:37 UTC, fanf commented
PR updated with a new commit

2021-02-20 09:39 UTC, Normation-Quality-Assistant commented
This PR is not mergeable to upper versions.
Since it is "Ready for merge" you must merge it by yourself using the following command:
`rudder-dev merge https://github.com/Normation/rudder/pull/3514`
-- Your faithful QA
Kant merge: "To be is to do."
 (https://ci.normation.com/jenkins/job/merge-accepted-pr/35759/console)

2021-02-20 09:39 UTC, fanf commented
OK, squash merging this PR

2021-02-20 09:40 UTC, merged