Fixes #18999: when we install a plugin, if the dependency (package manager) is not met, it still tries to install it and fails
Normation/rudder pull request #3551
Opened 2021-03-19 14:59 UTC by ncharles

https://issues.rudder.io/issues/18999

2021-03-19 15:00 UTC, ncharles commented
Commit modified

2021-03-19 15:36 UTC, Fdall requested changes

2021-03-19 15:36 UTC, Fdall commented on relay/sources/rudder-pkg/lib/rudder-pkg/rudderPkgUtils.py
>        else:
You should add a case in the same way that the "binary" type was defined. I am pretty sure we want to have typed dependencies and so, an "apt" and a "rpm" type of dependencies..

2021-03-22 14:15 UTC, ncharles commented
PR updated with a new commit

2021-04-12 08:30 UTC, Fdall approved these changes

2021-04-16 06:56 UTC, Normation-Quality-Assistant commented
This PR is not mergeable to upper versions.
Since it is "Ready for merge" you must merge it by yourself using the following command:
`rudder-dev merge https://github.com/Normation/rudder/pull/3551`
-- Your faithful QA
Kant merge: "Happiness is not an ideal of reason, but of imagination."
 (https://ci.normation.com/jenkins/job/merge-accepted-pr/37766/console)

2021-04-16 06:58 UTC, fanf commented
OK, squash merging this PR

2021-04-16 07:08 UTC, fanf commented
OK, merging this PR

2021-04-16 07:23 UTC, fanf commented
OK, merging this PR

2021-04-16 07:25 UTC, fanf commented
OK, merging this PR

2021-04-16 07:30 UTC, peckpeck commented
OK, merging this PR

2021-04-16 09:02 UTC, VinceMacBuche commented
OK, merging this PR

2021-04-16 09:03 UTC, merged