Fixes #19576: Add system configuration object for scale-out-relay plugin
Normation/rudder pull request #3734
Opened 2021-07-27 00:40 UTC by fanf

https://issues.rudder.io/issues/19576

2021-07-27 07:20 UTC, ncharles requested changes
i would really enjoy a comment

2021-07-27 07:20 UTC, ncharles commented on webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/servers/PolicyServerManagementService.scala
> +  def directiveCommonHasPolicyServer(nodeId: NodeId, hostname: String, policyServerId: NodeId) = {
this signature is super confusing: i would expect the policyServerId to be the final policyServerId (so the relay id) - i think it needs either a comment or better method naming

2021-07-27 08:41 UTC, fanf commented
PR updated with a new commit

2021-07-28 16:28 UTC, ncharles approved these changes

2021-07-28 16:29 UTC, Normation-Quality-Assistant commented
OK, squash merging this PR

2021-07-28 16:29 UTC, merged