Fixes #19753: Make rule categories editable
Normation/rudder pull request #3808
Opened 2021-08-10 16:28 UTC by RaphaelGauthier

https://issues.rudder.io/issues/19753

2021-08-10 19:18 UTC, ncharles requested changes
Looks great to me. Can you change the comment and self merge?

2021-08-10 19:18 UTC, ncharles commented on webapp/sources/rudder/rudder-web/src/main/elm/rules/sources/ViewCategoryDetails.elm
> +-- This file contains all methods to display the details of the selected rule.
```suggestion
-- This file contains all methods to display the details of the selected category.
```

2021-08-17 12:46 UTC, RaphaelGauthier commented
Commit modified

2021-08-17 13:09 UTC, RaphaelGauthier commented
PR rebased

2021-08-17 13:44 UTC, Normation-Quality-Assistant commented
OK, merging this PR

2021-08-17 13:44 UTC, merged