Fixes #19776: result condition are canonifying variables
Normation/rudder pull request #3828
Opened 2021-08-18 22:45 UTC by VinceMacBuche

https://issues.rudder.io/issues/19776

2021-08-18 22:59 UTC, VinceMacBuche commented
PR updated with a new commit

2021-08-19 08:21 UTC, amousset requested changes
I'd love to have tests for this parser, this type of regex in the editor had some recurring bugs

2021-08-19 11:06 UTC, VinceMacBuche commented
PR updated with a new commit

2021-08-19 18:05 UTC, amousset approved these changes

2021-08-19 18:06 UTC, Normation-Quality-Assistant commented
OK, squash merging this PR

2021-08-19 18:06 UTC, merged