Fixes #20460: Invalid attribute 'special:all_servers_with_role' (or special:all_nodes_without_role) for entry ruleTarget
Normation/rudder pull request #4065
Opened 2021-12-20 22:38 UTC by fanf

https://issues.rudder.io/issues/20460

2021-12-20 22:45 UTC, fanf commented
PR updated with a new commit

2021-12-21 08:03 UTC, ncharles requested changes
It looks good, except that one test is failing nsureNodeLoaded(com.normation.rudder.services.queries.TestQueryProcessor): assertion failed: Not found the expected number of entries in test LDAP directory [expected: 80, found: 81], perhaps the demo entries where not correctly loaded

2021-12-21 08:49 UTC, fanf commented
PR updated with a new commit

2021-12-21 08:49 UTC, ncharles approved these changes

2021-12-21 17:35 UTC, fanf commented
OK, squash merging this PR

2021-12-21 17:36 UTC, merged

2021-12-27 15:27 UTC, ncharles commented on webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/policies/RuleTarget.scala
> +}
this is missing the unser part of the file

2021-12-27 15:43 UTC, ncharles commented on webapp/sources/rudder/rudder-core/src/main/resources/ldap/bootstrap.ldif
> +
the group doesn't show up in the rule page