Fixes #24550: Nodes table should not be displayed in every tab of group details
Normation/rudder pull request #5538
Opened 2024-03-26 15:40 UTC by clarktsiory

https://issues.rudder.io/issues/24550
![Peek 2024-03-27 16-55](https://github.com/Normation/rudder/assets/65616064/a22829ee-8dbc-4ba7-81ee-f8540e1d52e1)

2024-03-26 16:12 UTC, clarktsiory commented
PR updated with a new commit

2024-03-26 16:19 UTC, clarktsiory commented
PR updated with a new commit

2024-03-26 16:26 UTC, clarktsiory commented
PR updated with a new commit

2024-03-26 16:33 UTC, clarktsiory commented
PR updated with a new commit

2024-03-26 16:35 UTC, clarktsiory commented
PR updated with a new commit

2024-03-27 13:15 UTC, fanf commented on webapp/sources/rudder/rudder-web/src/main/scala/com/normation/rudder/web/components/SearchNodeComponent.scala
> +        ) // we need to set something, or IE moans
I think that comment can be removed :)

2024-03-27 15:02 UTC, VinceMacBuche requested changes
The node list should only be displayed in Critera and summary at least that what i expected

2024-03-27 15:55 UTC, clarktsiory commented
PR updated with a new commit

2024-04-03 12:47 UTC, Normation-Quality-Assistant commented
This PR is not mergeable to upper versions.
Since it is "Ready for merge" you must merge it by yourself using the following command:
`rudder-dev merge https://github.com/Normation/rudder/pull/5538`
-- Your faithful QA
Kant merge: "To be is to do."
 (https://ci.normation.com/jenkins/job/merge-accepted-pr/82711/console)

2024-04-12 09:29 UTC, Normation-Quality-Assistant commented
This PR is not mergeable to upper versions.
Since it is "Ready for merge" you must merge it by yourself using the following command:
`rudder-dev merge https://github.com/Normation/rudder/pull/5538`
-- Your faithful QA
Kant merge: "Science is organized knowledge. Wisdom is organized life."
 (https://ci.normation.com/jenkins/job/merge-accepted-pr/83106/console)

2024-04-16 15:54 UTC, clarktsiory commented
OK, squash merging this PR

2024-04-16 15:55 UTC, merged