Fixes #25841: Create an instance id on each root server
Normation/rudder pull request #6025
Opened 2024-11-18 08:54 UTC by clarktsiory

https://issues.rudder.io/issues/25841

2024-11-18 09:01 UTC, clarktsiory commented
Commit modified

2024-11-18 09:01 UTC, clarktsiory commented
Commit modified

2024-12-17 08:58 UTC, clarktsiory commented
Commit modified

2024-12-17 09:04 UTC, clarktsiory commented
Commit modified

2024-12-17 21:56 UTC, fanf commented on webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/RudderConfig.scala
> +    lazy val instanceIdService   = InstanceIdService.make(instanceUuidPath, instanceIdGenerator).runNow
We will want to expose it in the `RudderConfigApi` (in `rci = init()` and then add one line with trait signature and the corresponding service.

2024-12-17 21:57 UTC, fanf requested changes
Looks good, it just need to be exposed in `RudderConfigApi`

2024-12-18 08:01 UTC, clarktsiory commented
PR rebased

2024-12-18 09:34 UTC, Normation-Quality-Assistant commented
OK, merging this PR

2024-12-18 09:34 UTC, merged