Fixes #26046: Migrate compliance status from lift-json to zio-json
Normation/rudder pull request #6086
Opened 2024-12-16 07:04 UTC by fanf

https://issues.rudder.io/issues/26046

2025-01-08 22:02 UTC, fanf commented
PR updated with a new commit

2025-01-08 22:19 UTC, fanf commented
PR updated with a new commit

2025-01-08 22:20 UTC, fanf commented
PR updated with a new commit

2025-01-08 22:21 UTC, fanf commented on webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/ComplianceLevel.scala
> -)
moved in the end of the file, with other serialization things

2025-01-08 22:39 UTC, fanf commented
PR updated with a new commit

2025-01-08 22:39 UTC, fanf commented
PR updated with a new commit

2025-01-09 17:30 UTC, clarktsiory reviewed
LGTM, just some suggestions/questions

2025-01-09 17:33 UTC, clarktsiory requested changes

2025-01-09 17:33 UTC, clarktsiory commented on webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/ComplianceLevel.scala
> +    ComplianceSerializable.apply.tupled(x.sized(nbFields).map(_.tupled).get)
However this does not seem to compile...
I'm not sure how to fix that, but why not ! I remember having used [kittens](https://github.com/typelevel/kittens) with macros for something similar (to derive a Monoid#empty)

2025-01-09 17:45 UTC, fanf commented on webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/services/quicksearch/QuickSearchBackendImpl.scala
> +import com.normation.rudder.domain.policies.Tags as TAGS
BECAUSE
(there is a name clash, and this one is used only one time)

2025-01-09 21:01 UTC, fanf commented on webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
> +      .withFieldComputed(_.status, _._2.transformInto[ApiStatusInfo])
yep,it works now (with a `2` in second line)

2025-01-09 21:06 UTC, fanf commented on webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
> +  }
the existing one is for thing of the same type: `ComplianceLevel` is the number of things in each kind, and `ComplianceLevelSerialisation` the corresponding json. 
This one is changing the type from level to percent. It's a local tool because almost all reports have the percent, so just removing boilerplate in the other transformers.

2025-01-09 21:07 UTC, fanf commented on webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/ComplianceLevel.scala
> +    ComplianceSerializable.apply.tupled(x.sized(nbFields).map(_.tupled).get)
ah yes, shapeless need a real integer and not `nbFields`

2025-01-09 21:14 UTC, fanf commented on webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/domain/reports/StatusReports.scala
> +@nowarn("msg=private val .* in object NodeStatusReportSerialization is never used")
:+1:

2025-01-10 10:32 UTC, Normation-Quality-Assistant commented
OK, merging this PR

2025-01-10 10:32 UTC, merged